services:

  mbsn_db:
    image: postgres:16
    container_name: mbsn_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0123"
      POSTGRES_DB: mbsn
    ports:
      - "5400:5432"
    networks:
      - net_mbsn
#    volumes:
#      - pgdata:/var/lib/postgresql/data


  mbsn_web:
    build: .
    container_name: mbsn_web
#    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - mbsn_db
    environment:
      DATABASE_URL: postgres://postgres:0123@mbsn_db:5400/mbsn
    ports:
      - "5000:5000"
    networks:
      - net_mbsn

#volumes:
#  pgdata:

networks:
  net_mbsn:
    name: net_mbsn
    driver: bridge
