services:
  db_mbsn:
    image: postgres:16
    container_name: mbsn_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0123"
      POSTGRES_DB: mbsn
    ports:
      - "5400:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    networks:
#      - mbsn

#docker-compose down
#docker-compose up --build